import { useQuery } from "@apollo/client";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";

import { GET_QUESTIONS } from "queries";
import QuestionView from "components/QuestionView";

import { useToggle } from "hooks";
import CreateQuestion from "../../components/CreateQuestion";
import Link from "next/link";

const SurveyPage = () => {
  const {
    query: { surveyId },
  } = useRouter();

  const { data } = useQuery(GET_QUESTIONS, {
    skip: !Boolean(surveyId),
    variables: { surveyId },
  });
  const questions = data?.Survey?.Questions || [];

  const [showCreate, toggleCreateForm] = useToggle();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        <Link href="/">Home</Link>
      </h1>

      <button onClick={toggleCreateForm}>Create Question</button>

      <main className={styles.main}>
        {showCreate && <CreateQuestion closeForm={toggleCreateForm} />}
        {questions.map((question, index) => (
          <QuestionView {...question} index={index} key={question.id} />
        ))}
      </main>
    </div>
  );
};

export default SurveyPage;
