import { useQuery } from "@apollo/client";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import SurveyView from "../components/SurveyView";

import { GET_SURVEYS } from "../queries";
import { useToggle } from "hooks";
import CreateSurvey from "../components/CreateSurvey";

const Home = () => {
  const { data } = useQuery(GET_SURVEYS);
  const surveys = data?.allSurveys || [];

  const [showCreate, toggleCreateForm] = useToggle();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>List of Surveys</h1>
      <button onClick={toggleCreateForm}>Create Form</button>

      <main>
        {showCreate && <CreateSurvey closeForm={toggleCreateForm} />}
        {surveys.map((survey, index) => (
          <SurveyView {...survey} index={index} key={survey.id} />
        ))}
      </main>
    </div>
  );
};

export default Home;
